### ISSUE TITLE
msrv raised by indirect dependency on serde

### ISSUE THREAD

**Issue by victorjulien** [CybercentreCanada/sawp#3]
Through the indirect dependency on `serde`, the MSRV is getting a significant bump. Sadly, the `serde` project doesn't seem to care (see https://github.com/serde-rs/serde/issues/2255)
```
├── sawp-modbus v0.11.1
│   ├── nom v5.1.2 (*)
│   ├── num_enum v0.5.7
│   │   └── num_enum_derive v0.5.7 (proc-macro)
│   │       ├── proc-macro-crate v1.1.0
│   │       │   ├── thiserror v1.0.32
│   │       │   │   └── thiserror-impl v1.0.32 (proc-macro)
│   │       │   │       ├── proc-macro2 v1.0.43 (*)
│   │       │   │       ├── quote v1.0.21 (*)
│   │       │   │       └── syn v1.0.99 (*)
│   │       │   └── toml v0.5.9
│   │       │       └── serde v1.0.143
│   │       ├── proc-macro2 v1.0.43 (*)
│   │       ├── quote v1.0.21 (*)
│   │       └── syn v1.0.99 (*)
│   ├── sawp v0.11.1 (*)
│   └── sawp-flags v0.11.1
│       └── sawp-flags-derive v0.11.1 (proc-macro)
│           ├── proc-macro-crate v1.1.0 (*)
│           ├── proc-macro2 v1.0.43 (*)
│           ├── quote v1.0.21 (*)
│           └── syn v1.0.99 (*)
```

**Comment by cccs-wecorre** [comment]
Hello, we are currently investigating this and a similar issue with an indirect dependency from Criterion. We are committed to keeping our MSRV in-line with Suricata.

**Comment by victorjulien** [comment]
Thanks for looking into this!

2 things:
1. serde did address the issue, but is still vague about a MSRV commitment in general
2. in Suricata, for the upcoming 7 release, we bumped to 1.58. This excludes current Debian Stable, but we felt this started to lag too much to consider (https://redmine.openinfosecfoundation.org/issues/4163#note-17)

**Comment by cccs-wecorre** [comment]
Closing since Serde has addressed the issue. Our internal CI will strictly check MSRV requirements to try and catch these issues earlier.
