### ISSUE TITLE
Declare MIT license in cargo.toml

### ISSUE THREAD

**Issue by bmbenson** [CybercentreCanada/sawp#7]
Your libraries are marked non-standard licensing in crates.io due to the use of license-file instead of an [SPDX License expression](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) in your cargo.toml(s).

Other crates have similar setup with an MIT license with the copyright holder declared - IE: [tokio](https://github.com/tokio-rs/tokio/blob/master/tokio-util/LICENSE)

I am happy to make a PR, but wanted to open a dialogue in case there is something I may have missed.

**Comment by cccs-wecorre** [comment]
Thanks for bringing this up, taking a look at it we do appear to be using the license/license-file keys incorrectly. We would gladly accept a PR if you choose to submit one, otherwise I will fix it for our next release.

**Comment by bmbenson** [comment]
Is it possible to do a minor version bump & publish to crates.io?
Thank you!

**Comment by cccs-wecorre** [comment]
I appreciate the patience. We do have a release planned with a few other changes in the pipe. Time permitting I will try to push a release including this change, either with or without those.

**Comment by bmbenson** [comment]
Sounds good, thank you!

**Comment by cccs-wecorre** [comment]
Thanks again for patiently waiting. This change has been released with sawp 0.13.0 and is now available on crates.io.

**Comment by bmbenson** [comment]
Thank you very much!  I see it's now properly tagged with the MIT license on crates.io.
