### ISSUE TITLE
how to use the Length field in sawp_modbus

### ISSUE THREAD

**Issue by phoenixikkifullstack** [CybercentreCanada/sawp#9]
Hi, there:
I expect to use the @length field in struct Message (sawp/sawp_modbus/src/lib.rs)
however ,it's private in struct Message.
###
pub struct Message {
    pub transaction_id: u16,
    pub protocol_id: u16,
    length: u16,
    pub unit_id: u8,
    pub function: Function,
    #[cfg_attr(feature = "ffi", sawp_ffi(flag = "u8"))]
    pub access_type: Flags<AccessType>,
    #[cfg_attr(feature = "ffi", sawp_ffi(flag = "u8"))]
    pub category: Flags<CodeCategory>,
    pub data: Data,
    #[cfg_attr(feature = "ffi", sawp_ffi(flag = "u8"))]
    pub error_flags: Flags<ErrorFlags>,
}
###

Hope your response.
Sincerely.

**Comment by cccs-wecorre** [comment]
Thanks for filing an issue. The length field was added for assisting parsing and internal validation, but I see no reason why it shouldn't be public as it is a field parsed from the message. We will certainly fix that for you.

**Comment by cccs-wecorre** [comment]
Sawp 0.13.1 is released to crates.io now and includes this fix.

**Comment by phoenixikkifullstack** [comment]
Thanks for your support

> Thanks for filing an issue. The length field was added for assisting parsing and internal validation, but I see no reason why it shouldn't be public as it is a field parsed from the message. We will certainly fix that for you.
